export const TABLE_RESIZE = 'TABLE_RESIZE'
export const TABLE_TEXT_CHANGE = 'TABLE_TEXT_CHANGE'
export const TABLE_CELL_CHANGE = 'TABLE_CELL_CHANGE'
export const TABLE_STYLE_CHANGES = 'TABLE_STYLES_CHANGE'
